export const TopbarBg = "#18AC6A"
export const TopbarDarkBg = "#138A55"
export const TopbarLightBg = "#2FE292"
export const OldTopbarBg = "#333A42"
export const LightText = "white"
export const DarkText = "black"
export const BoxBg = "#F9F9F9"
export const GrayText = "#B0B0B0"
export const FormFieldBg = "#D9D9D9"
export const FormSubmitBg = "#5DC496"

export const TableBgOdd = "#EAEAEA"
export const TableBgEven = "#E0E0E0"
export const TableCellEdited = "#97e38e"